languageCode = "en-gb"
title = "BookStack"
baseurl = "https://bookstackapp.com/"
theme="bookstack"
enableGitInfo=true

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      xHTML = true

[permalinks]
  post = "/blog/:slug/"

[params]
  blogCover = "/images/cover.jpg"
  googleAnalyticsUserID = "UA-61486258-4"
